### ISSUE TITLE
登录了一段时间之后断线

### ISSUE THREAD

**Issue by Daydaylw3** [danni-cool/wechatbot-webhook#116]
日志的报错如下：

```
wxBotWebhook  | [2024-01-09T13:23:27.002] [INFO] - starting fetching api: http://192.168.2.90:7777/receive/msg 
wxBotWebhook  | [2024-01-09T13:23:31.225] [ERROR] - 
wxBotWebhook  | AssertionError: 3 == 0
wxBotWebhook  |  
wxBotWebhook  | [2024-01-09T13:23:31.226] [INFO] - starting fetching api: http://192.168.2.90:7777/receive/msg 
wxBotWebhook  | [2024-01-09T13:23:35.955] [ERROR] - 
wxBotWebhook  | AssertionError: 3 == 0
wxBotWebhook  |  
wxBotWebhook  | [2024-01-09T13:23:35.957] [ERROR] - 
wxBotWebhook  | Error: 连续3次同步失败，5s后尝试重启
wxBotWebhook  |  
wxBotWebhook  | [2024-01-09T13:23:35.957] [INFO] - starting fetching api: http://192.168.2.90:7777/receive/msg 
wxBotWebhook  | [2024-01-09T13:23:35.959] [INFO] - starting fetching api: http://192.168.2.90:7777/receive/msg 
wxBotWebhook  | [2024-01-09T13:23:42.162] [ERROR] - uncaughtException Error: must logout first before login again!
wxBotWebhook  |     at PuppetWechat4u.login (/app/node_modules/.pnpm/wechaty-puppet@1.20.2_rxjs@7.8.1/node_modules/wechaty-puppet/dist/cjs/src/mixins/login-mixin.js:84:23)
wxBotWebhook  |     at Wechat.<anonymous> (/app/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.13_@swc+core@1.3.101_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:318:24)
wxBotWebhook  |     at Wechat.emit (node:events:517:28)
wxBotWebhook  |     at /app/node_modules/.pnpm/wechat4u@0.7.14/node_modules/wechat4u/lib/wechat.js:202:16
wxBotWebhook  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

想知道这种情况重启镜像，会自动重新登陆回去吗（假定自动登录的参数为 true）

**Comment by danni-cool** [comment]
不会，这个是微信风控策略

**Comment by danni-cool** [comment]
重新扫码也可以，但是有bug，暂时没时间修，还是建议重启容器

**Comment by Daydaylw3** [comment]
> 重新扫码也可以，但是有bug，暂时没时间修，还是建议重启容器

如果我在发生这个报错之前就重启了容器，能规避这个问题吗？

比如我每个小时重启一次容器 @danni-cool

**Comment by danni-cool** [comment]
可以多看下faq关于这个问题的讨论，目前无解web协议就会掉线的，登录web微信也一样
