### ISSUE TITLE
AssertionError [ERR_ASSERTION]: -1 == 0

### ISSUE THREAD

**Issue by chenkaidog** [danni-cool/wechatbot-webhook#125]
[ERROR] - AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (/app/node_modules/.pnpm/wechat4u@0.7.14/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/.pnpm/wechat4u@0.7.14/node_modules/wechat4u/lib/core.js:537:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetWechat4u.messageSendText (/app/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.13_@swc+core@1.3.101_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:641:9)
    at async WechatifiedUserClass.say (/app/node_modules/.pnpm/wechaty@1.20.2_@swc+core@1.3.101_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:300:23)
    at async Object.formatAndSendMsg (/app/src/service/msgSender.js:486:9)
    at async /app/src/route/msg.js:152:34
    at async dispatch (/app/node_modules/.pnpm/hono@3.11.11/node_modules/hono/dist/cjs/compose.js:51:17)
    at async module.exports.loginCheck (/app/src/middleware/loginCheck.js:15:3)
    at async dispatch (/app/node_modules/.pnpm/hono@3.11.11/node_modules/hono/dist/cjs/compose.js:51:17) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: -1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'

what's wrong? please help

**Comment by danni-cool** [comment]
https://github.com/danni-cool/wechatbot-webhook/issues/60，这个问题是由于重新登录但是底层数据合并有问题，暂时重启解决
