### ISSUE TITLE
RECVD_MSG_API 连续收到1328次AssertionError

### ISSUE THREAD

**Issue by ShiFangJuMie** [danni-cool/wechatbot-webhook#160]
**提bug前先检查以下是否已经执行**

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**
我无法确定是否与 #140 属于相同问题，如果是因为掉线原因引发的话，我有2个补充信息
1、凌晨2点我有收到过机器人发的通知（截图中记录的时间有时区问题~）
2、我对healthz接口做了每60秒一次健康检查，如果失败会用另一个通道（企业微信的群聊机器人）告警，但我没有收到

我无法判断是不是因为wechatbot是健康的，但“wechaty 一直没登出所以一直报错”，如果是相同问题请close~

主要报错确实是集中在3和1205，穿插了极少数几条其他的

![image](https://github.com/danni-cool/wechatbot-webhook/assets/9131886/8c54e2e9-02d7-4153-8c84-dfc374a0e7aa)
...省略...
![image](https://github.com/danni-cool/wechatbot-webhook/assets/9131886/5ef51276-a6c0-4bf6-9fd2-47d878cdca07)

**提供有用的信息**

```
{"event":"error","error":{"code":2,"details":"AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/util/global.js:79:24)
    at /app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/core.js:139:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"400 != 400","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/util/global.js:79:24)
    at /app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/core.js:139:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"user":null}
```

```
{"event":"error","error":{"code":2,"details":"Error: getaddrinfo EAI_AGAIN wx.qq.com
    at AxiosError.from (/app/node_modules/.pnpm/axios@1.6.2_debug@2.6.9/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/.pnpm/axios@1.6.2_debug@2.6.9/node_modules/axios/dist/node/axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:529:35)
    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.3_debug@2.6.9/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"getaddrinfo EAI_AGAIN wx.qq.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN wx.qq.com
    at AxiosError.from (/app/node_modules/.pnpm/axios@1.6.2_debug@2.6.9/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/.pnpm/axios@1.6.2_debug@2.6.9/node_modules/axios/dist/node/axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:529:35)
    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.3_debug@2.6.9/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"user":{"_events":{},"_eventsCount":0,"id":"@7726d23b06f50dfb04869a80489fc9cfb75857511c2d80b1194a7bec9e9b0fdb","payload":{"alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=979771654&username=@7726d23b06f50dfb04869a80489fc9cfb75857511c2d80b1194a7bec9e9b0fdb&skey=@crypt_f7795e3d_b89cf6a8830ed9d37197536d619fb76d","friend":false,"gender":0,"id":"@7726d23b06f50dfb04869a80489fc9cfb75857511c2d80b1194a7bec9e9b0fdb","name":"NotifyBot & RSS","phone":[],"signature":"","star":false,"type":1}}}
```

**Comment by danni-cool** [comment]
这个问题我也一直在测试，掉线wechaty层面不会提示掉线，目前还是在通过特定的assert错误去手动触发登出事件，https://github.com/danni-cool/wechatbot-webhook/blob/005565c23d27fa10c763a7fd980902c7de2294c1/src/route/login.js#L56
