### ISSUE TITLE
扫码登录后自动登出

### ISSUE THREAD

**Issue by D1NOOO** [danni-cool/wechatbot-webhook#258]
## bug描述
扫码后，过几秒钟直接退出

所以请按以下格式描述问题：

- **场景**：
- docker容器部署
- **操作**：
- 调用/healthz接口提示unhealthy后，扫码登录
- **表现**：
- 扫码成功登陆后，直接登出并提示
[2024-11-04T19:05:14.264] [INFO] - Or Access the URL to login: http://localhost:3001/login?token=xxx
[2024-11-04T19:05:14.326] [INFO] - 🌱 User Contact<PANDA(AI版)> logged in 
[2024-11-04T19:05:14.327] [INFO] - 💬 你的推消息 api 为：http://localhost:3001/webhook/msg/v2?token=xxx 
[2024-11-04T19:05:14.328] [INFO] - 📖 发送消息结构 API 请参考: https://github.com/danni-cool/wechatbot-webhook?tab=readme-ov-file#%EF%B8%8F-api
 
[2024-11-04T19:05:14.546] [ERROR] - 
AssertionError: '1102' == 0
 
[2024-11-04T19:05:14.548] [INFO] - User Contact<PANDA(AI版)> logout 
[2024-11-04T19:05:14.560] [ERROR] - 
AssertionError: 1102 == 0
 
[2024-11-04T19:05:14.565] [ERROR] - 
AssertionError: 1101 == 0
 
[2024-11-04T19:05:14.570] [ERROR] - 
AssertionError: 1101 == 0
 
[2024-11-04T19:05:14.800] [INFO] - ✨ 扫描以下二维码以登录 ✨

..........

## 提供有用的信息
- 目前使用的版本号：latest镜像

**Comment by D1NOOO** [comment]
[2024-11-04T19:14:57.594] [WARN] - 19:14:57 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: -1 == 0) wechat4u.batchGetContact() exception: undefined 
[2024-11-04T19:14:57.746] [ERROR] - uncaughtException Error: must logout first before login again!
    at PuppetWechat4u.login (/app/node_modules/.pnpm/wechaty-puppet@1.20.2_patch_hash=wwr5xvwazgbyb26ud6vwdruala_rxjs@7.8.1/node_modules/wechaty-puppet/dist/cjs/src/mixins/login-mixin.js:84:23)
    at Wechat.<anonymous> (/app/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.13_patch_hash=nq4vns7vah46g6vxziyzqg5jey_@swc+core@1.3.101_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:318:24)
    at Wechat.emit (node:events:517:28)
    at /app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/wechat.js:204:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by D1NOOO** [comment]
这似乎是一个偶现的bug，停止容器后，再重启又可以正常登录了。

**Comment by qwertrewqwertrewq** [comment]
对，我也遇到了，重启后才正常。希望大佬能修复

**Comment by mark988** [comment]
我也是使用的最新版本，登录后直接退出。
![Uploading 截屏2025-01-09 16.22.57.png…]()

**Comment by linux-y** [comment]
> 这似乎是一个偶现的bug，停止容器后，再重启又可以正常登录了。

不是偶发，我重启docker或者重启容器都没用，登录后3秒左右直接闪退，试了十来次都不行
`wxbot_app       | [2025-01-10T02:54:22.186] [INFO] - Message: Message#Unknown[🗣Contact<报警机器人>]	 
wxbot_app       | [2025-01-10T02:54:24.465] [INFO] - Message: Message#Unknown[🗣Contact<报警机器人>]	 
wxbot_app       | [2025-01-10T02:54:26.718] [ERROR] - 
wxbot_app       | AssertionError: '1102' == 0
wxbot_app       |  
wxbot_app       | [2025-01-10T02:54:26.719] [INFO] - User Contact<报警机器人> logout`

**Comment by chen-xiaochen** [comment]
![image](https://github.com/user-attachments/assets/b877cc4d-027a-4469-9535-a09e0072500d)
同样的问题，1月1日的时候没有问题，但现在 虚拟机环境 和 服务器环境均报错

**Comment by chen-xiaochen** [comment]
目前测试出的情况是   账号被风控了
登录网页版微信还能登录就没事 不能登录就是被动态风控了

能否解封未知！！！
