### ISSUE TITLE
使用收消息接口返回同意好友时发生错误

### ISSUE THREAD

**Issue by RichardMiku** [danni-cool/wechatbot-webhook#264]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [ ] 我已更新了最新版本的代码
- [ -] 我已经仔细地阅读了readme 文档
- [ -] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
使用接口同意好友时发生错误

所以请按以下格式描述问题：

2024-11-14 21:25:46 [2024-11-14T13:25:46.312] [ERROR] - 尝试回应好友邀请时发生错误: AssertionError [ERR_ASSERTION]: -1 == 0
2024-11-14 21:25:46     at Object.equal (/app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/util/global.js:69:24)
2024-11-14 21:25:46     at /app/node_modules/.pnpm/wechat4u@0.7.14_patch_hash=mmirz2kximouh53sl2jk76abxe/node_modules/wechat4u/lib/core.js:1210:24
2024-11-14 21:25:46     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-14 21:25:46     at async PuppetWechat4u.friendshipAccept (/app/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.13_patch_hash=nq4vns7vah46g6vxziyzqg5jey_@swc+core@1.3.101_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:827:9)
2024-11-14 21:25:46     at async WechatifiedUserClass.accept (/app/node_modules/.pnpm/wechaty@1.20.2_@swc+core@1.3.101_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/wechaty/dist/cjs/src/user-modules/friendship.js:225:9)
2024-11-14 21:25:46     at async handleResSendMsg (/app/src/service/msgSender.js:625:11)
2024-11-14 21:25:46     at async Object.onRecvdFriendship (/app/src/service/friendship.js:28:9)
2024-11-14 21:25:46     at async WechatyImpl.<anonymous> (/app/src/wechaty/init.js:117:7) {
2024-11-14 21:25:46   generatedMessage: true,
2024-11-14 21:25:46   code: 'ERR_ASSERTION',
2024-11-14 21:25:46   actual: -1,
2024-11-14 21:25:46   expected: 0,
2024-11-14 21:25:46   operator: '==',
2024-11-14 21:25:46   response: [Object],
2024-11-14 21:25:46   tips: '通过好友请求失败'
2024-11-14 21:25:46 } 

## 提供有用的信息
- 目前使用的版本号：目前使用的是docker hub中的最新镜像

**Comment by danni-cool** [comment]
web协议 这个接口经常被Tencent 封所以目前还是别依赖这个功能，做正常文件收发吧
