### ISSUE TITLE
程序初始化失败，点击确认刷新网页

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/wechatbot-webhook#93]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/40719048/b56e5639-3cbe-473c-988a-72fd430803e0)

无法发送消息了，然后登录web端，发现了这样的问题

**Comment by danni-cool** [comment]
? 和这个项目有关吗

**Comment by glwhappen** [comment]
因为项目报错了，而且使用的是web协议，我就想着登录上网页端看看

`
2023-12-24 17:33:24   '{"event":"error","error":{"code":2,"details":"AssertionError [ERR_ASSERTION]: 400 != 400\\n    at Object.notEqual (/app/node_modules/wechat4u/lib/util/global.js:79:24)\\n    at /app/node_modules/wechat4u/lib/core.js:139:24\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"400 != 400","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: 400 != 400\\n    at Object.notEqual (/app/node_modules/wechat4u/lib/util/global.js:79:24)\\n    at /app/node_modules/wechat4u/lib/core.js:139:24\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"user":null}',
2023-12-24 17:33:24   [Function: bound ]
2023-12-24 17:33:24 ]
2023-12-24 17:33:24 HTTP error When trying to send Data to RecvdApi: 500
`

**Comment by danni-cool** [comment]
这种一般是微信已经掉了，但是wechaty 还没提示logout，重启容器登录是否可以解决
